language: rust
rust:
- stable
- beta
- nightly
os:
- linux
- osx
- windows
cache: cargo
script:
- cargo build --verbose --all
- cargo test --verbose --all
jobs:
  allow_failures:
  - rust: nightly
  include:
  - stage: publish
    script: cargo publish
    if: (type = push) && (tag =~ ^[0-9])
